name: slugnutrition
description: "UCSC personalized menu plans"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  line_awesome_flutter: ^2.0.0
  flutter_svg: ^2.0.9
  image_picker: ^1.0.7
  editable_image: ^2.0.0

  ## -- STATE MANAGEMENT
  get: ^4.6.6
  flutter_riverpod: ^2.4.10


  ## -- OnBoarding PACKAGES
  liquid_swipe: ^3.0.0
  smooth_page_indicator: ^1.0.0+2

  ## -- OTP TEXT FIELD PACKAGE
  flutter_otp_text_field: ^1.1.1
  ## -- FIREBASE PACKAGES
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.3
  flutter_facebook_auth: ^6.0.3
  google_sign_in: ^6.1.6
  shared_preferences: ^2.2.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/logo.png
    - assets/images/bread.png
    - assets/images/onboarding_images/
    - assets/images/welcome_images/
    - assets/logo/
    - assets/images/dashboard/
    - assets/images/forget_password/
    - assets/images/profile/
    - assets/images/bmi/
    - assets/images/meals/

