// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQqm6bWBmytmulUwyRUStOoq4A39BVx-Q',
    appId: '1:887468987324:android:ab2a92884298ac097711b9',
    messagingSenderId: '887468987324',
    projectId: 'slugnutrition',
    databaseURL: 'https://slugnutrition-default-rtdb.firebaseio.com',
    storageBucket: 'slugnutrition.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_pwIMOKYi5IYiNxnj2R9N0EEOFuGGn_8',
    appId: '1:887468987324:ios:efa124e8a95453187711b9',
    messagingSenderId: '887468987324',
    projectId: 'slugnutrition',
    databaseURL: 'https://slugnutrition-default-rtdb.firebaseio.com',
    storageBucket: 'slugnutrition.appspot.com',
    iosClientId: '887468987324-mrbmd7pub7fqm13oajjjpflu88luc9e4.apps.googleusercontent.com',
    iosBundleId: 'com.example.slugnutrition',
  );
}